use_default_settings:
  engines:
    keep_only:
      - duckduckgo
      - wikipedia
      - bing

server:
  port: 8080
  bind_address: 0.0.0.0
  secret_key: ${SEARXNG_SERVER_SECRET_KEY}
  image_proxy: true

general:
  debug: false

search:
  safe_search: 0
  autocomplete: google
  formats:
    - html
    - json
engines: []  # Engines are defined in keep_only above
